argonne-lcf/THAPI

- ze/gen_ze.rb
- ze/tracer_ze_helpers.include.c
- ze/ze_model.rb
Test thoroughly, review thoroughly.
> Added support for dumping profiling info on command list reset.

- xprof/xprof.sh.erb.in
- ze/Makefile.am
- ze/gen_babeltrace_ze_lib.rb
- ze/gen_babeltrace_ze_model.rb
- ze/gen_probe_base.rb
- ze/gen_ze.rb
- ze/gen_ze_library.rb
- ze/gen_ze_structs_tracepoints.rb
- ze/gen_zel_structs_tracepoints.rb
- ze/gen_zes_structs_tracepoints.rb
- ze/gen_zet_structs_tracepoints.rb
- ze/tracer_ze.sh.in
This should dump linked structs as well. Trace display should be improved.
> Linked structs

- xprof/xprof.sh.erb.in
- ze/gen_ze.rb
- ze/tracer_ze.sh.in
- ze/tracer_ze_helpers.include.c
@TApplencourt You'll need to incorporate the option in iprof before we can merge.
> Added option to enable chained structs tracing.

- ze/tracer_ze_helpers.include.c
- ze/ze_model.rb
Despite: https://spec.oneapi.io/level-zero/latest/core/PROG.html#kernel-timestamp-events
> Fix event scope.

- ze/headers.patch
- ze/include/layers/zel_tracing_register_cb.h
- ze/include/ze_api.h
- ze/include/ze_ddi.h
- ze/include/zes_api.h
- ze/include/zes_ddi.h
- ze/include/zet_api.h
- ze/include/zet_ddi.h
- ze/ze_meta_parameters.yaml
- ze/zes_meta_parameters.yaml
> Level zero v1.4.0

- ze/tracer_ze_helpers.include.c
In the case when an event is rest, the command list should still be able to be used. 
This change should avoid failing to register events while enqueuing tasks in a command list, when an event that was using this command list is being unregistered.
> Don't remove command list from pool when resetting event.

- utils/include/utarray.h
- utils/include/uthash.h
- utils/include/utlist.h
There has been important changes.
> Upgraded uthash and utarray to latest versions.

- .github/workflows/presubmit.yml
- configure.ac
This adds the metababel gem into the CI workflow and configure.ac for validation.
> Add metababel to CI and configure.ac

- opencl/Makefile.am
Fixes: https://github.com/argonne-lcf/THAPI/issues/95
> Fix dependencies on static probes generation.

- xprof/xprof.sh.erb.in
This implements what we discussed last week.
> Add option to disable device profiling.

- cuda/Makefile.am
- cuda/cudart.h.include
- cuda/extract_cudart.rb
- cuda/gen_cudart.rb
- cuda/gen_cudart_linker_script.rb
- cuda/gen_cudart_tracepoints.rb
- cuda/headers.patch
- cuda/include/__cudart.h
- cuda/include/cuda_profiler_api.h
- cuda/include/cuda_vdpau_interop.h
- cuda/tracer_cuda.sh.in
Still missing GL and EGL APIs.
> Added missing cudart APIs.

- configure.ac
- m4/m4_ax_ruby_extension.m4
> Add version check for gems.

- cuda/Makefile.am
- ze/Makefile.am
Fixes https://github.com/argonne-lcf/THAPI/issues/125
> Use group target for header patching.

- hip/Makefile.am
> Add group target for hip.

- xprof/btx_timeline.cpp
- xprof/perfetto_prunned.proto
Now that perfetto  is more "mature" (aka fixed some bug) we should definitely rewrite the timeline... It was a hacky good first try, but plotting the stream seam more important the pid
> Fix timeline

- utils/xprof_utils.cpp
- utils/xprof_utils.hpp
- xprof/interval.c.erb
- xprof/interval.h.erb
- xprof/interval_model.yaml
- xprof/timeline.cpp
- xprof/timeline.hpp
- ze/zeinterval_callbacks.cpp.erb
- ze/zeinterval_callbacks.hpp
Add awareness of hostname to the timeline.
> Cleanup of babeltrace and lttng power/frequency code.

- cuda/cuda_model.rb
- cuda/gen_cuda.rb
- cuda/tracer_cuda_helpers.include.c
> Add stub implementation of CUDA symbols to avoid segfaulting.

- xprof/xprof.rb.in
Thanks @colleeneb  for the report!
> Handle ctrl-c

- .github/workflows/presubmit.yml
- integration_tests/test.bats
- xprof/perfetto_prunned.proto
🎉 
Should be merged after #181 but it's kind of working
> Integration test

- xprof/xprof.rb.in
- Add back `--sampling`. 
- I took the opportunity to add better support for the ENV variable already set.
> Xprof sampling2

- xprof/xprof.rb.in
> Fix -1 in the argv

- integration_tests/iprof_mpi_daemon_test/mpi_hello_world.cpp
- integration_tests/iprof_mpi_daemon_test/test.sh
- integration_tests/test.bats
Adds CI test for MPI daemon. Not sure if the paths are correct for it to launch the test correctly.
> add iprof MPI daemon test

- integration_tests/iprof_mpi_daemon_test/test.sh
Just make it easier to comment out stuff
> Update MPI test.sh

- configure.ac
- cuda/tracer_cuda_helpers.include.c
- sampling/thapi_sampling.c
- sampling/thapi_sampling.h
- utils/babeltrace_thapi.in
- xprof/btx_timeline.cpp
- xprof/perfetto_prunned.proto
- ze/btx_zeinterval_callbacks.cpp
- ze/btx_zeinterval_callbacks.hpp
- ze/tracer_ze_helpers.include.c
FIx:
- remove old pretty printed
- Use lttng ts to print correct start
- Remove `name` in counter
Todo:
- Need to fix malloc / calloc  in ze_tracer_helper.c
- Also need may want to add `unit` to the protobuff (for watt, and %), https://perfetto.dev/docs/reference/trace-packet-proto#CounterDescriptor  (and use unit_multiplier if required)
> fix sample

- .github/workflows/presubmit.yml
- xprof/sync_daemon_fs
- xprof/xprof.rb.in
- Forbide user to make typo of FIX_FS
- Allow more control on where the lock is placed (aka use a different shared FS, this is the case on aurora where we should use flare and not HOME @colleeneb idea)
> more control of FS

- .github/workflows/presubmit.yml
- integration_tests/mpi_sync_daemon.bats
- integration_tests/sync_daemon_test/test.sh
It was a transient error.  :( 
Adding more log, so at least we will know next time which bash command hanged
> More log and timeout in the CI

- xprof/xprof.rb.in
> Fix blocking in xprof

- xprof/xprof.rb.in
Split babeltrace2_thapi , and the post-process
> Refac xprof for archive

- utils/babeltrace_thapi.in
This will help later when need to do the same to change the source with `archive.`
(not that this removes a limitation of before who was useless)
> Thapi Minor refactor

- cuda/btx_cudainterval_callbacks.cpp
- cuda/btx_cudamatching_model.yaml
Some memcpy exit didn't get their associated `entry`. We where missing some traffic entry .
I don;t know if I compute the `size` of the data transfert correctly
> add missing entry

- .github/workflows/presubmit.yml
- ze/Makefile.am
- ze/tracer_ze_helpers.include.c
- Update dependency and fix bugs (??) related to them.
- All improve a little nit the  CI with some variable
> Dependency update

- cuda/Makefile.am
- cuda/tracer_cuda.sh.in
- hip/Makefile.am
- hip/tracer_hip.sh.in
- mpi/Makefile.am
- mpi/tracer_mpi.sh.in
- mpi/tracer_mpi_helpers.include.c
- omp/Makefile.am
- opencl/Makefile.am
- opencl/tracer_opencl.sh.in
- xprof/Makefile.am
- xprof/xprof.rb.in
- ze/Makefile.am
- ze/tracer_ze.sh.in
- Found a bug in `mpi` (didn't checked the correct ENV, fixed)
> remove `install-hook`

- xprof/xprof.rb.in
datadir -> DATADIR
(found by solomon)
> Fix ze minimal

- utils/babeltrace_thapi.in
> More error checking for trace folder (Fix #306)

- cuda/gen_cuda_library_base.rb
- hip/gen_hip_library_base.rb
- mpi/gen_mpi_library_base.rb
- omp/gen_omp_library_base.rb
- utils/gen_library_base.rb
- ze/gen_ze_library_base.rb
(sorry, I was not able to resist the `map` refactoring)
Verified that it produce identical ruby library
> cleanup_to_ffi_name

- .github/actions/setup-thapi/action.yml
- .github/workflows/presubmit.yml
> Refactor ci

- ze/gen_ze_library.rb
- ze/ze_bindings_base.rb
> Fix hand written ffi types.

- opencl/btx_clinterval_callbacks.cpp
Reported by @nscottnichols  (who knew Nathan did lot of OpenCL...)
> Fix opencl stack

- configure.ac
Will send a separate PR to update spack package.
> Use `--disable-sync-daemon-mpi`
