argonne-lcf/THAPI

xprof/interval.c.erb

Kind of ugly, but the clean way is done by metababel.
This component is really horrible and should be replaced soon...

We should send Begin and End messages

---

cuda/cuda_model.rb

`cuGetProcAddress` and `cuGetProcAddress_v2` can be called before cuInit, therefore they should be init functions as well.
This fixes OpenACC tracing with recent CUDA versions.

Add cuGetProcAddress* to list of initi functions.

---

xprof/xprof.sh.erb.in

So because of pipefail the error of `broken pipe` (which can appear when doing something like `foo | head -1`)  will make all the programs stop silently.
This fix this by using `|| true` 
(Kind of important, as `iprof -r` is currently broken :( )

Fix pipefail

---

xprof/xprof.sh.erb.in

`$(stat -c %h $SHARED_GLOBAL_FILESYSTEM) != 2`  doesn't work as I Was thinking...
```
tapplencourt@gene-lxc:~$ ls /home/tapplencourt/.thapi_lock/
toto  toto2
tapplencourt@gene-lxc:~$ stat /home/tapplencourt/.thapi_lock/
File: /home/tapplencourt/.thapi_lock/
Size: 18        	Blocks: 0          IO Block: 4096   directory
Device: 40h/64d	Inode: 13666303    Links: 1
Access: (0775/drwxrwxr-x)  Uid: ( 1003/tapplencourt)   Gid: ( 1003/tapplencourt)
Access: 2023-07-27 17:13:07.923096752 -0500
Modify: 2023-07-27 17:11:41.057635055 -0500
Change: 2023-07-27 17:11:41.057635055 -0500
Birth: 2023-07-27 17:01:50.455485424 -0500
```
```
applenco@x1921c0s1b0n0:~> ls .thapi_lock/
0  1
applenco@x1921c0s1b0n0:~> stat .thapi_lock/
File: .thapi_lock/
Size: 4096      	Blocks: 8          IO Block: 4096 …
```

Fix xprosh.sh

---

xprof/btx_timeline.cpp

Before a recent c++ compiler complains (it did on my Ubuntu 23.04).

Fix -Werror=maybe-uninitialized

---

cuda/extract_cuda_versions.rb

`cuGetProcAddress` version where in incorrect order in the header leading to only `cuGetProcAddress_v2` being traced. This enforces the correct ordering.

APIs need to be in reverse order of their versions.

---

xprof/xprof.sh.erb.in

$(USER) doesn't work, it's $USER... :( 
One more reason to re-write it in ruby :(

Fix `USER`

---

configure.ac
xprof/btx_aggreg.cpp
xprof/btx_tally.cpp
xprof/btx_timeline.cpp

We updated the `register_callbacks_initialize/finalize_usr_data` to `register_callbacks_initialize/finalize_component`

Update to metababel 1.0.0 interface

---

utils/babeltrace_thapi.in
xprof/xprof.rb.in

This adds some  `on-node` processing. 
Need to add some more options to add flexibility on where to save data and with step / processes to perform.
(Sorry for some typo change, it's rubocopt doing is thing...) 
- Added a `no-muxer` to babeltrace_thapi
- Add this `on-node-processing` concept to xprof.

Add on node processing

---

configure.ac
utils/xprof_utils.hpp
xprof/Makefile.am
xprof/sync_daemon_fs
xprof/xprof.rb.in

Based on an idea on @nscottnichols 
This PR add a new binary (`sync_daemon_fs`) who is responsible of performing 2 operation:
- A local node barrier
- A global barrier (more precisely all the "global master == rank 0) wait that all "local master" rank hit the barrier and then continue)
The communication is on `signal`, so need to for some loop. 
The end goal is to implement another daemon that will use MPI (for faster and more robust SYNC) using the same API.
Then a compile time, we can choose with daemon to use (the filesystem base one, or the MPI one).

Handle sync/barrier with external binary

---

xprof/xprof.rb.in

`https://en.wikipedia.org/wiki/ISO_8601` the `:` make it a little painful but still manageable (no need to escape) 
At least now we will use a standard 🤷🏽

use ISO8601

---

utils/babeltrace_thapi.in
xprof/xprof.rb.in

Due too stupidity (and potentially lack of consistency in naming...) `-k` was passed by default.
Thanks @colleeneb  for the report 
Fixed now:
```
applenco@x4407c1s4b0n0:~/THAPI/build> ./ici/bin/iprof --debug -r
THAPI: Trace location: /home/applenco/thapi-traces/thapi_aggreg--2024-03-04T16:19:47+00:00
I, [2024-03-04T17:23:13.389172 #193494]  INFO -- : postprocess /home/applenco/thapi-traces/thapi_aggreg--2024-03-04T16:19:47+00:00
BACKEND_ZE | 1 Hostnames | 1 Processes | 1 Threads |
Name |     Time | Time(%) | Calls |  Average |      Min |      Max | Error |
zeModuleCreate | 142.43ms |  95.22% |     1 | 142.43ms | 142.43ms | 142.43ms |     0 |
zeCommandListCreateImmediate |   1.95ms |   1.31% |     2 | 977.04us |  37.96us |   1.92ms |     0 |
zeCommandListAppendMemoryCopy |   1.11ms | …
```

Fix option parsing

---

ze/tracer_ze_helpers.include.c

Those were getting exported, I don't think it was intended.

Fix visibility of profiling symbols.

---

utils/babeltrace_thapi.in

For whatever reason, on Sunsopt, the module doesn't add LD_LIBRARY_PATH anymore, and everything relies on rpath.
But the `pkgconfig` was still set so `(PROTOBUF_LIBS)` was founded at configure time, but the plugins was not able to be load.
```
export LD_LIBRARY_PATH=/opt/aurora/23.275.2/spack/gcc/0.6.1/install/linux-sles15-x86_64/gcc-12.2.0/protobuf-3.21.12-twja3abpf3vamx3eb2iz67inuxx7v5v5/lib64:$LD_LIBRARY_PATH
```
Did the trick.
Anyway, improve the error message when one plugin cannot be loaded

better error message when plugin not found

---

utils/babeltrace_thapi.in
utils/optparse_thapi.rb
xprof/xprof.rb.in

- Fix bug with new optparse version 
```
applenco@x1921c0s1b0n0:~> /home/applenco/THAPI/build/ici/bin/babeltrace_thapi to_aggreg --output /home/applenco/thapi-traces/thapi_aggreg--a06dd29ebbde112468050513ca3c9cdf/x1921c0s1b0n0 --backends cl,ze,omp -- /tmp/thapi--a06dd29ebbde112468050513ca3c9cdf/x1921c0s1b0n0
ERROR: wrong number of arguments (given 4, expected 2)
Usage: babeltrace_thapi to_aggreg [OPTIONS] trace_directory...
--output OUTPUT
-h, --help                       Prints this help
-b, --backends BACKENDS          Default: omp,cl,ze,cuda,hip
--debug                      Default: false
--[no-]muxer
-v, --version                    Print the version string
__
For complaints, praises, or bug reports please use: <(o )___
https://github.com/argonne-lcf/THAPI              ( ._> /
or send …
```

Improve Parsing

---

xprof/Makefile.am

This fixes an issue where sync_daemon_mpi.c is not include in the dist tarball. Regardless of what is available on the machine running make dist, all sources should be included in case MPI is available on the machine the tarball is actually used.

mpi: always include mpi sync daemon in dist

---

cuda/btx_cudainterval_callbacks.cpp
cuda/tests/interval_profiling_cuda_memcpy.bt_text_pretty
omp/btx_ompinterval_callbacks.cpp
omp/tests/data_op.bt_text_pretty
omp/tests/data_op_emi.bt_text_pretty
opencl/btx_clinterval_callbacks.cpp
opencl/tests/command_queue.bt_text_pretty
opencl/tests/command_queue_other_thread.bt_text_pretty
opencl/tests/enqueue_read_buffer_fast.bt_text_pretty
opencl/tests/interleave_process.bt_text_pretty
opencl/tests/interleave_thread.bt_text_pretty
opencl/tests/results_first.bt_text_pretty
opencl/tests/with_error.bt_text_pretty
xprof/btx_aggreg.cpp
xprof/btx_aggreg_model.yaml
xprof/btx_interval_model.yaml
xprof/btx_tally.cpp
xprof/tests/aggreg_to_tally.thapi_aggreg_text_pretty
xprof/tests/interval_to_aggreg.bt_text_pretty
xprof/tests/interval_to_aggreg.thapi_interval_text_pretty
ze/btx_zeinterval_callbacks.cpp
ze/btx_zeinterval_callbacks.hpp
ze/btx_zematching_model.yaml

- Add metadata for traffic 
- Add error checking for traffic (not sending traffic message if error)
- For profiled commands, use event errors 
- For non-profiled commands (zeMakeResidant and co), created a `_exit` callback

Improve Traffic

---

xprof/xprof.rb.in
ze/btx_zeinterval_callbacks.cpp

Need to clean up the associated events to the command list, when the command list is reset.
If not old event (who are trigger at the end) will have wrong born-min

Fix non imm

---

xprof/xprof.rb.in

MPI is doing billions of those call, and not that useful

Remove some event in default ze

---

xprof/xprof.rb.in

Only the master should check if the file already exists; if not, it's a stupid race condition.

only master should check if file exist

---

xprof/Makefile.am
xprof/btx_aggreg.cpp

Added aggreg callback in aggreg,
Maybe it makes more sense to create new components which do the same for `aggregate` and `interval` messages, and we call this new component `merge-trace.`. So we don't put the logic of `add callback on the event you create just in the case you need to merge them in the same trace` in a separate component.
We can even create a new component like a stripper in metababel who does that, not transferring events he doesn't know, but putting all the event he knows in the same trace and dropping the ones he doesn't know.
🤷🏽

Add aggreg callback in aggreg

---

utils/babeltrace_thapi.in
xprof/xprof.rb.in

When `traced-ranks` is used, some hostname may have no trace. It was tripping `babeltrace_thapi`.
Change:
- `babeltrace_thapi` just warn if the trace is empty (will still raise if no metadata)
- `xprof` doesn't assume that the `master` node has a metadata.yaml; just find the first one available.
Thanks @khossain4337 for the bug report.

Handle empty hostname in trace

---

utils/babeltrace_thapi.in
xprof/btx_aggreg.cpp
xprof/btx_aggreg_params.yaml
xprof/xprof.rb.in

@colleeneb have a MPI job (512) where the final reply of aggregations take for ever. I suspect if due to too much metadata
(she have million of different size of the MPI traffic)
By default let not trace the medatada, but keep them when using `-k`
```
applenco@x4315c6s0b0n0:~/slow> /home/applenco/THAPI/build/ici/bin/iprof ./a.out | grep "zeCommandListAppendMemoryCopy"
THAPI: Trace location: /home/applenco/thapi-traces/thapi_aggreg--2024-07-17T17:17:22+00:00
zeCommandListAppendMemoryCopy | 724.56us |   0.37% |    15 |  48.30us |  10.23us | 489.08us |     0 |
zeCommandListAppendMemoryCopy(S2M) |  8.96us |  12.61% |     4 |   2.24us |  2.08us |  2.40us |
zeCommandListAppendMemoryCopy(M2D) |  5.68us |   8.00% |     7 | 811.43ns |    80ns |  2.88us |
zeCommandListAppendMemoryCopy(D2H) | …
```

Discard Metadata

---

xprof/xprof.rb.in

Last PR to prepare for the `archive`.
In archive we need to
- lttng stop
- wait for bt2 to finish
- kill daemon sessiond
so need to split those 2 functions.

split session and sessiond

---

utils/babeltrace_thapi.in

Before the check to add muxer was in the `graph` instensiation.  Was super ugly

Better muxer

---

.github/workflows/presubmit.yml
integration_tests/light_iprof_only_sync.sh
integration_tests/mpi_helloworld.c
integration_tests/parallel_execution.bats
xprof/sync_daemon_mpi.c

Add Mpi tests

---

cuda/cuda_model.rb

Prevent wrapping unsupported version of CUDA functions.

---

.github/workflows/presubmit.yml
integration_tests/light_iprof_only_sync.sh
integration_tests/parallel_execution.bats
xprof/sync_daemon_mpi.c
xprof/xprof.rb.in

All processes are now calling the SYNC_Daemon.
- This allows us to use a regular MPI barrier and avoid some subtle MPI behavior.
- FIx also the integration test to do only MPI global barrier. (limitation of the FS daemon)

Fix Daemon (and integration)

---

integration_tests/light_iprof_only_sync.sh

To avoid race conditions, `SIGNAL_RECEIVED` needs to be set  before spawning or signaling the daemon

Fix Race Condition numero2323

---

.github/workflows/presubmit.yml
integration_tests/general.bats
utils/babeltrace_thapi.in
xprof/xprof.rb.in

add archive

---

xprof/xprof.rb.in

Reported by @zippylab 
Before:
```
applenco@aurora-uan-0011:~> iprof adasd
Traceback (most recent call last):
5: from /opt/aurora/24.180.0/spack/unified/0.8.0/install/linux-sles15-x86_64/oneapi-2024.07.30.002/thapi-git.ceaabfca6a67a0714c44fea8c49d24fc00559485_master-2il6zxsni7z7edscone7b2py6zeztzyr/bin/iprof:840:in `<main>'
4: from /opt/aurora/24.180.0/spack/unified/0.8.0/install/linux-sles15-x86_64/oneapi-2024.07.30.002/thapi-git.ceaabfca6a67a0714c44fea8c49d24fc00559485_master-2il6zxsni7z7edscone7b2py6zeztzyr/bin/iprof:649:in `trace_and_on_node_processing'
3: from /opt/aurora/24.180.0/spack/unified/0.8.0/install/linux-sles15-x86_64/oneapi-2024.07.30.002/thapi-git.ceaabfca6a67a0714c44fea8c49d24fc00559485_master-2il6zxsni7z7edscone7b2py6zeztzyr/bin/iprof:309:in `open'
2: from …
```

Better error message when bin doesn't exist

---

xprof/xprof.rb.in
ze/Makefile.am

Fix @abagusetty  bug, where the new mpich was hanging iprof.
It was due to `yakza` checking for the `soname` of our tracing library and expecting it to match `ze_loader`.
Working now
```
applenco@x4516c1s7b0n0:~/mpi_hang> mpirun -n 1 -- ~/THAPI/build/ici/bin/iprof -- ./a.out
THAPI_SYNC_DAEMON_MPI Warning: Did not get MPI_THREAD_SINGLE, got MPI_THREAD_MULTIPLE
Hello world from processor x4516c1s7b0n0, rank 0 out of 1 processors
THAPI: Trace location: /home/applenco/thapi-traces/thapi_aggreg--2024-10-11T16:43:44+00:00
BACKEND_MPI | 1 Hostnames | 1 Processes | 1 Threads |
Name |     Time | Time(%) | Calls |  Average |      Min |      Max |
MPI_Init | 505.26ms |  98.31% |     1 | 505.26ms | 505.26ms | 505.26ms |
MPI_Finalize |   8.66ms |   1.68% |     1 |   8.66ms |   8.66ms |   8.66ms | …
```

fix_ze_soname

---

xprof/xprof.rb.in

- 2.7.2 have be verified on Aurora (we should add  test of ruby version on the CI -- either here or on the spack one)
- Removing Endless rand to avoid a syntax error when try to run iprof with ruby 2.5 (default on aurora -- reported by @sbekele81 )
```
(0..).each do |i|
^
/home/sbekele/fabric_stat/bin/iprof:234: syntax error, unexpected keyword_end, expecting ')'
end
^~~
```

Add Ruby version Check

---

xprof/xprof.rb.in

Fix the 
```
/home/videau/opt/thapi/0.0.7/bin/iprof:884:in `exit': no implicit conversion from nil to integer (TypeError)
exit(XprofExitCode.get)
^^^^^^^^^^^^^^^^^
from /home/videau/opt/thapi/0.0.7/bin/iprof:884:in `<main>'
```
Now return:
```
applenco@x4307c2s4b0n0:~/THAPI/build> ./ici/bin/iprof ./a.out
E, [2024-10-11T22:13:11.385479 #181857] ERROR -- : ./a.out returned with a nil exit code (most probably due to a segault
THAPI: Trace location: /home/applenco/thapi-traces/thapi_aggreg--2024-10-11T22:13:12+00:00
[...]
```
The clean way should be that PTY print the segfault. But I don't know how to do it... It print std err nornaly, but not the segfault message :( 
```
#include <stdio.h>
int main ()
{
printf ("%s", 'a');
}
```
Simple segfaulting binary if one want to reproduce.

Handle nil return code

---

xprof/xprof.rb.in

I introduced a bug when doing "merge conflict" resolution last time.
Note to myself: next time, after `rebasing,` re-run the CI manually.

Fix "update" in xprof in devel

---

xprof/xprof.rb.in
ze/sampling_daemon.c

Few minor change. 
One change is that all the daemons are using the same signals (make code re-use easier).  Maybe we want each daemon to have an independent set of signal numbers? Right now, it's not a problem, as we call it the Daemon serially.

Sampling Refactoring

---

utils/gen_library_base.rb

This will be required once the cast-to-yaml gem gets updated, but can be safely used in the meantime.

Fixed unamed members in ruby FFI composites.

---

utils/gen_library_base.rb

After this patch, we should not have any :uintxx_t inside the generated ruby libraries, but :uintxx
Will need to fix babeltrace2 bindings as well

Fix ffi fixed sized integers.

---

ze/gen_ze.rb
ze/ze_model.rb

Should allow tracing exported extensions queried through zeDriverGetExtensionFunctionAddress.

Add exported extension to zeDriverGetExtensionFunctionAddress.

---

xprof/xprof.rb.in

Before, sampling daemon didn't get the ENV variable set by xprof.
- That mean it was broken, as the LD_LIBRARY_PATH was not set, so was not able to find the tracing.so lib. It was working just because the spack module was setting the LD_LIBRARY_PATH
- @nscottnichols PR will put back SAMPLING env, right now it make it hang if we put it due to bugs in the ze sampling code.
- In the future, we can just not set `LD_LIBRARY_PATH` for the sampling daemon, this should simplify the ze sampling daemon a lot by allowing him to call direcly ZE symbol and not dlopen the "original" lib

Fix sampling daemon not getting the env

---

.github/workflows/presubmit.yml
integration_tests/abnormal_usr_bin_exit.bats
integration_tests/backend_mpi.bats
integration_tests/general.bats
integration_tests/parallel_execution.bats
integration_tests/sampling.bats
integration_tests/setup_suite.bash
integration_tests/test_env_vars.bash

Also, set all the env vars in a common file. This will make it easier to run tests manually
and through spack in the future.

Use default values for test env vars

---

configure.ac
m4/ax_cxx_compile_stdcxx.m4

Not sure if it will crash or need to do a 
```
if test "$HAVE_CXX17" = "yes"; then
AC_MSG_RESULT([C++17 support is enabled])
else
AC_MSG_ERROR([C++17 support is required but not found])
fi
```
If somebody will a old gcc can try will be nice

add c++17 check
